services:
  - type: web
    name: django-api
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py createsuperuser --noinput || true
    startCommand: gunicorn edenites_be.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: edenites_be.settings
      - key: DJANGO_SUPERUSER_USERNAME
        value: strongcode
      - key: DJANGO_SUPERUSER_EMAIL
        value: emmanueludoh360@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: Strongcode
      - key: SECRET_KEY
        value: django-insecure-_p!ml3uw&6du#zmosns060wm$oh*dfe1-2un7cnxxxq@ljm^ff
      - key: DATABASE_URL
        fromDatabase:
          name: e-learning-db
          property: connectionString