# Generated by Django 4.2.20 on 2025-04-27 15:40

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=254, unique=True)),
        ),
    ]
