# Generated by Django 4.2.20 on 2025-06-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jambquestion',
            name='correct_index',
        ),
        migrations.RemoveField(
            model_name='jambquestion',
            name='options',
        ),
        migrations.CreateModel(
            name='JAMBOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Label (A, B, C, D)', max_length=1)),
                ('text', models.CharField(help_text='Text of this answer option', max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='jamb.jambquestion')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('question', 'label')},
            },
        ),
        migrations.AddField(
            model_name='jambquestion',
            name='correct_option',
            field=models.ForeignKey(blank=True, help_text='The correct answer for this question.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jamb.jamboption'),
        ),
    ]
