# Generated by Django 4.2.20 on 2025-06-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamb', '0002_remove_jambquestion_correct_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jambquestion',
            name='correct_option',
        ),
        migrations.AddField(
            model_name='jambquestion',
            name='correct_index',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jambquestion',
            name='options',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='JAMBOption',
        ),
    ]
