# Generated by Django 4.2.20 on 2025-06-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamb', '0003_remove_jambquestion_correct_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jambquestion',
            name='correct_index',
        ),
        migrations.RemoveField(
            model_name='jambquestion',
            name='options',
        ),
        migrations.AddField(
            model_name='jambquestion',
            name='correct_choice',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='Select A, B, C, or D as the correct answer.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jambquestion',
            name='option_a',
            field=models.CharField(max_length=255, null=True, verbose_name='Option A'),
        ),
        migrations.AddField(
            model_name='jambquestion',
            name='option_b',
            field=models.CharField(max_length=255, null=True, verbose_name='Option B'),
        ),
        migrations.AddField(
            model_name='jambquestion',
            name='option_c',
            field=models.CharField(max_length=255, null=True, verbose_name='Option C'),
        ),
        migrations.AddField(
            model_name='jambquestion',
            name='option_d',
            field=models.CharField(max_length=255, null=True, verbose_name='Option D'),
        ),
    ]
