# Generated by Django 4.2.20 on 2025-06-03 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamb', '0004_remove_jambquestion_correct_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JAMBOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='Mark True for the correct answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='jamb.jambquestion')),
            ],
        ),
    ]
