# Generated by Django 4.2.20 on 2025-05-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('JAMB', 'JAMB'), ('WAEC', 'WAEC')], max_length=4)),
                ('year', models.PositiveSmallIntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('solution_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('exam_type', 'year', 'subject')},
            },
        ),
    ]
