# Generated by Django 4.2.20 on 2025-06-04 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('JAMB', 'JAMB'), ('WAEC', 'WAEC'), ('NECO', 'NECO'), ('JSCE', 'Junior WAEC/JSCE'), ('FSLC', 'FSLC')], max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('question_text', models.TextField()),
                ('solution_text', models.TextField(help_text='Official solution/explanation.')),
                ('allow_multiple', models.BooleanField(default=False, help_text='If True, more than one choice may be correct.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_questions', to='exams.examsubject')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('exam_type', 'year', 'subject', 'question_text')},
            },
        ),
        migrations.CreateModel(
            name='PastOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.pastquestion')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('question', 'label')},
            },
        ),
    ]
