# Generated by Django 4.2.20 on 2025-05-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastquestion',
            name='allow_multiple',
            field=models.BooleanField(default=False, help_text='If true, more than one option may be correct'),
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='exam_type',
            field=models.CharField(choices=[('JAMB', 'JAMB'), ('WAEC', 'WAEC'), ('NECO', 'NECO'), ('Junior WAEC/JSCE', 'Junior WAEC/JSCE'), ('FSLC', 'FSLC')], max_length=20),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='Mark True for correct answers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.pastquestion')),
            ],
        ),
    ]
