# Generated by Django 4.2.20 on 2025-06-03 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_pastquestion_allow_multiple_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='label',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='allow_multiple',
            field=models.BooleanField(default=False, help_text='More than one option may be correct'),
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='exam_type',
            field=models.CharField(choices=[('JAMB', 'JAMB'), ('WAEC', 'WAEC'), ('NECO', 'NECO'), ('JSCE', 'Junior WAEC/JSCE'), ('FSLC', 'FSLC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='solution_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='pastquestion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_questions', to='exams.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='pastquestion',
            unique_together={('exam_type', 'year', 'subject', 'question_text')},
        ),
    ]
