# Generated by Django 4.2.20 on 2025-06-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followupoption',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='quizoption',
            options={'ordering': ['label']},
        ),
        migrations.AddField(
            model_name='followupquestion',
            name='solution_text',
            field=models.TextField(help_text='Official solution/explanation.', null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='solution_text',
            field=models.TextField(help_text='Official solution/explanation.', null=True),
        ),
    ]
