# Generated by Django 4.2.20 on 2025-07-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_followupoption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='If True, this course shows up in the featured list.'),
        ),
    ]
