# Generated by Django 4.2.20 on 2025-06-03 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_quiz_course_is_free_alter_category_name_and_more'),
        ('content', '0003_lesson_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_choice',
        ),
        migrations.AddField(
            model_name='question',
            name='allow_multiple',
            field=models.BooleanField(default=False, help_text='If true, more than one option may be marked correct'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_lessons', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.lesson'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], help_text='Choose exactly one letter (A, B, C, …) per option', max_length=1)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='Mark True if this option is correct for the question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.question')),
            ],
            options={
                'unique_together': {('question', 'label')},
            },
        ),
    ]
